-- Rollback: drop all tables in reverse dependency order

DROP TABLE IF EXISTS interview_questions CASCADE;
DROP TABLE IF EXISTS teacher_analyses CASCADE;
DROP TABLE IF EXISTS themes CASCADE;
DROP TABLE IF EXISTS categories CASCADE;
DROP TABLE IF EXISTS patterns CASCADE;
DROP TABLE IF EXISTS analysis_runs CASCADE;
DROP TABLE IF EXISTS pipeline_jobs CASCADE;
DROP TABLE IF EXISTS report_items CASCADE;
DROP TABLE IF EXISTS reports CASCADE;
DROP TABLE IF EXISTS event_mappings CASCADE;
DROP TABLE IF EXISTS checklist_items CASCADE;
DROP TABLE IF EXISTS checklists CASCADE;
DROP TABLE IF EXISTS raw_events CASCADE;
DROP TABLE IF EXISTS video_chunks CASCADE;
DROP TABLE IF EXISTS videos CASCADE;
DROP TABLE IF EXISTS users CASCADE;

DROP EXTENSION IF EXISTS "uuid-ossp";
